### ISSUE TITLE
Take user to Update Page after creating new Skill/Resource

### ISSUE THREAD

**Issue by jkluse** [agile-learning-institute/mentorHub-topic-ui#11]
Make following changes: 
1 - After mentor adds name for a skill/resource, redirect to the edit page for the newly created skill/resource (currently stays on topic page and shows an topic item with an edit button. Once user is done adding information to skill/resource, the back button should take them back to the topic page.

2 - On the topic page, update the skill/resource list item button text from 'edit' to 'more'

**Comment by FlatBallFlyer** [comment]
as I think about this more, it might be a good idea to have a "Done" button on the resource and skill pages that does the same thing as a "back" for them.
